name: Schedule Scoring

on:
  schedule:
    - cron: '50 0/1 * * *'
jobs:
  trigger_scoring_if_needed:
    name: Schedule Scoring
    runs-on: ubuntu-latest
    steps:
    - name: Check epoch timing
      run: |
        epoch_info=$(curl -sfLS "http://api.mainnet-beta.solana.com" -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}')
        current_epoch=$(<<<"$epoch_info" jq '.result.epoch' -r)
        slot_index=$(<<<"$epoch_info" jq '.result.slotIndex' -r)

        last_scoring_epoch=$(find scoring -type d | sort -n | tail -1 | cut -d/ -f2 | cut -d. -f1)

        echo "Current epoch: $current_epoch"
        echo "Current slot: $slot_index"

        if (( "$slot_index" > 300000 )) && (( $last_scoring_epoch != current_epoch ))
        then
          echo "Would trigger the scoring pipeline"
        fi
